### ISSUE TITLE
Moved jus repos to a GitHub organization!

### ISSUE THREAD

**Issue by zeke** [jus/jus#54]
Hey @wmhilton @elingerojo @jdormit I moved jus to an org, so I am not a bottleneck to the project's improvement.

If you are joining, please:

- wield your admin access responsibly.
- Continue using PRs, and wait for someone to review before merging. See http://openopensource.org
- mark your membership as public, so the org looks more legit.
- adhere to the [Contributor Covenant](http://contributor-covenant.org/)
- send me your npm username so I can give you npm publish access.

**Comment by wmhilton** [comment]
Am totally humbled and honored! 😊 I can't guarantee this promotion will result in spontaneous contributions... but it will definitely make it easier to share any enhancements or bugfixes I generate as I scratch my own itches. :)
