### ISSUE TITLE
jus development stalled by Node 4 support

### ISSUE THREAD

**Issue by elingerojo** [jus/jus#77]
### Events summary

1. `node-oniguruma` [broke Node 4 support](https://github.com/atom/node-oniguruma/issues/65) on April 20
2. The above make `jus` development imposible 'cause of Travis
3. There has been three PRs ( #72, #73 and #74) to mitigate `jus` impact to no avail
4. `node-origumma` problem has been [fixed](https://github.com/atom/node-oniguruma/pull/71) on Sep. 8
5. `first-mate` is  [blocking the update to origuruma@7.0.0](https://github.com/atom/first-mate/blob/master/package.json#L25) in the dependency chain (marky-markdown > highlights > first-mate > oniguruma)

### Issue

`jus` development can not be done 'cause of Travis (I have not been able to PR since April 20)

#### a) Ask 'first-mate' to update oniguruma dependency

Create a `first-mate` PR with just one line change in their `package.json`. ~~The change consist in just one character `"oniguruma": "6.2.1",` to `"oniguruma": "^6.2.1",` ...and hope it gets merged.~~

EDIT: The change consist in  `"oniguruma": "6.2.1",` to `"oniguruma": "7.0.0",`

This may be difficult 'cause I see their tests and configurations stating Node 6 clearly and may not have an incentive to support Node 4 ...but you never know.

#### b) Change 'jus' Node support to 6

Create and merge a `jus` PR with the needed change.

**Comment by elingerojo** [comment]
### Possible options

#### a) Ask 'first-mate' to update oniguruma dependency

 ✔️  done by `first-mate` [PR](https://github.com/atom/first-mate/pull/98)

#### b) Change 'jus' Node support to 6

 ✔️ done by `jus` #78

<hr>

Let's see which one wins! 😕

**Comment by djfdev** [comment]
@elingerojo Would love to see this resolved. I see there is a 3rd option implemented in #79, and it looks like tests are passing. What's the status of this?

**Comment by zeke** [comment]
Hey @djfdev I think it's ready to go, if @elingerojo says so.
