### ISSUE TITLE
Dynamic pages, filtering data, custom helpers, and other templating languages?

### ISSUE THREAD

**Issue by brandonweiss** [jus/jus#84]
I'm coming from Middleman and looking for a Node-based static site generator that is similar in its simplicity, and I think Jus might be it, but there are some (I think) simple things I want to do that I can't figure out how to do with Jus, and I'm not sure if that's because they're not documented or they're not currently possible.

**Dynamic pages**

Is it possible to loop through the data in a data file and generate pages? For example, if the data file had an array of objects, each with a category, you might want to generate a page for each category that then lists the objects in the data file.

**Filtering data from a data file**

Is it possible to manipulate the data/context before being passed to the handlebars template? Many of my static sites can't store the data in the exact that it would be outputted and the data needs to be filtered/transformed first.

**Custom helpers**

Is it possible to add custom handlebars helpers?

**Alternative templating languages**

Is it possible to add more/other templating languages? Handlebars and “logic-less” templates are useful in some circumstances, but the proliferation and necessity of logic helpers in Handlebars seems to point to the fact that maybe a templating language like EJS is more appropriate in many situations.

P.S. Thanks for making this! It looks great!

**Comment by djfdev** [comment]
As far as manipulating data/context, support for [handlebars-helpers](https://github.com/helpers/handlebars-helpers) was recently added, which includes lots of methods for array/collection manipulation. But this would take place in the handlebars template itself.

**Comment by brandonweiss** [comment]
@djfdev Yeah, I saw that. Unfortunately the sort of pre-transforming/manipulation I'm talking about would not really be possible with simple helpers. 😞

**Comment by zeke** [comment]
Hey @brandonweiss.

Thanks for considering Jus. I have to say though that I'm not actively maintaining it, and from the looks of it, it doesn't do many of the things you're looking for:

> Dynamic pages

Nope.

> Filtering data from a data file

Nope. You'll have to pre-filter it somehow.

> Custom helpers

Answered above ☝️ 

> Alternative templating languages

Nope. But in the past I was thinking https://github.com/tj/consolidate.js/ would be a nice way to do this.

All that said, if you feel like moving Jus forward an enabling it to do these kinds of things, I'm happy to help move that along.

**Comment by djfdev** [comment]
@zeke @brandonweiss It might be cool to introduce some sort of middleware API to jus. Not sure how this would look exactly, but I’m imagining some way to generalize building extensions and support for all these types of things without having to modify the jus repo directly.

**Comment by djfdev** [comment]
Potentially related to that ^ idea:

#24, #38, #41, #58, #76, #81

**Comment by zeke** [comment]
> middleware API to jus

I like this idea

**Comment by brandonweiss** [comment]
@zeke Thanks for getting back to me so quickly! I'm so embarrassed it took me this long to respond. 🙈

I waffled back and forth between proposing some small changes to jus and rolling my own project for some time, and eventually decided to roll my own. Mostly to learn, but also because I am equally opinionated and wanted to try doing a bunch of things in a different way.

Thanks!

**Comment by zeke** [comment]
Thanks for following up 👍
